version: 2

jobs:
  build:
    working_directory: ~/work
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt-get update
      - run: apt-get install -y git python3-pip
      - run: pip3 install -U pytest pytest-cov black flake8
      - checkout
      - run: pip3 install .
      # format and lint
      - run: LC_ALL=C.UTF-8 black --check setup.py tuna/ test/*.py
      - run: flake8 setup.py tuna/ test/*.py
